name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci
      - name: Run backend tests (CI)
        working-directory: backend
        run: npm run test:ci
      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage

  frontend-tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install frontend dependencies
        working-directory: gestion-proyectos-frontend
        run: npm ci
      - name: Run frontend tests (CI)
        working-directory: gestion-proyectos-frontend
        run: npm run test:ci
      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: gestion-proyectos-frontend/coverage
